name: pubspec for all modules
description: A new Flutter package project.

sdk: ">=2.17.0 <3.0.0"
flutter_sdk: ">=1.17.0"

dependencies:
  analyzer: 5.2.0
  animations: 2.0.3
  app_settings: 4.1.8
  appcheck: 1.0.5
  artemis: 7.1.0-beta.0
  async: 2.10.0
  auto_route: 5.0.4
  auto_route_generator: 5.0.3
  bloc_test: 9.0.3
  build_resolvers: 2.1.0
  build_runner: 2.2.0
  cached_network_image: 3.2.1
  camera: 0.9.4+5
  carousel_slider: 4.1.1
  cloud_firestore: 3.1.12
  connectivity_plus: 1.0.1
  crypto: 3.0.1
  cupertino_icons: 1.0.3
  custom_lint: 0.0.16
  custom_lint_builder: 0.0.16
  custom_pop_up_menu: 1.2.2
  dart_code_metrics: 5.1.0
  dart_style: 2.2.4
  dartx: 1.0.0
  decimal: 2.1.0
  device_info_plus: 4.0.0
  device_preview: 1.1.0
  dio: 4.0.1
  dio_cookie_manager: 2.0.0
  dotted_border: 2.0.0+2
  dropdown_button2: 1.6.2
  encrypted_shared_preferences: 2.0.0
  enum_to_string: 2.0.1
  equatable: 2.0.3
  expandable_page_view: 1.0.17
  firebase_analytics: 9.0.5
  firebase_core: 1.10.2
  firebase_core_platform_interface: 4.4.1
  firebase_crashlytics: 2.4.5
  firebase_messaging: 11.2.5
  firebase_remote_config: 1.0.4
  fl_chart: 0.55.1
  flutter_bloc: 8.0.1
  flutter_cache_manager: 3.3.0
  flutter_gen_runner: 4.1.6
  flutter_html: 3.0.0-alpha.5
  flutter_launcher_icons: 0.9.2
  flutter_linkify: 5.0.2
  flutter_lints: 2.0.1
  flutter_local_notifications: 12.0.4
  flutter_native_splash: 2.2.16
  flutter_native_timezone: 2.0.0
  flutter_portal: 1.1.1
  flutter_screenutil: 5.5.3+2
  flutter_svg: 1.1.6
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  geolocator: 8.2.1
  get_it: 7.2.0
  google_maps_flutter: 2.2.0
  gql: 0.13.0
  gql_dio_link: 0.1.0
  gql_exec: 0.3.0
  gql_link: 0.4.0
  graphql_flutter: 5.0.0
  health: 4.1.1
  http_proxy: 1.2.0
  image_picker: 0.8.4+4
  infinite_scroll_pagination: 3.2.0
  injectable: 2.1.0
  injectable_generator: 2.1.3
  intl: 0.17.0
  intl_utils: 2.8.1
  json_annotation: 4.7.0
  json_serializable: 6.5.4
  local_auth: 1.1.9
  location: 4.4.0
  meta: 1.8.0
  mime: 1.0.1
  mocktail: 0.3.0
  modal_bottom_sheet: 2.0.1
  objectbox: 1.4.1
  objectbox_flutter_libs: 1.4.1
  objectbox_generator: 1.4.1
  ogp_data_extract: 0.1.2
  optimized_cached_image: 3.0.0
  package_info_plus: 1.3.0
  path_provider: 2.0.7
  percent_indicator: 4.2.2
  permission_handler: 9.2.0
  photo_view: 0.13.0
  pull_to_refresh_flutter3: 2.0.1
  rxdart: 0.26.0
  sliding_up_panel: 2.0.0+1
  smooth_page_indicator: 1.0.0+2
  source_gen: 1.2.6
  sqflite: 2.0.2+1
  store_redirect: 2.0.1
  syncfusion_flutter_charts: 20.2.45
  table_calendar: 3.0.7
  timeago: 3.3.0
  timezone: 0.9.0
  tuple: 2.0.0
  uni_links: 0.5.1
  url_launcher: 6.0.17
  webview_flutter_android: 2.8.14
